yongchao: finish task1
A-Comosus/what-code-test pull request #2
Opened 2022-05-02 11:37 UTC by pycxu

2022-05-02 13:33 UTC, Crazyorchid requested changes
rewrite requested

2022-05-02 14:41 UTC, NorrisWu0 commented
Okay, apart from what Max has requested. You probably will want to check out how to write a commit message.

2022-05-02 14:42 UTC, NorrisWu0 requested changes
Either explain what you have done or re-write this in your own code.

2022-05-02 15:17 UTC, pycxu commented
> Either explain what you have done or re-write this in your own code.

I will rewrite the task as requested, create the backend first and try to write proper commit messages.

2022-05-02 19:15 UTC, pycxu commented
Created a backend server from scratch and refactored the react code with components.

2022-05-02 22:49 UTC, Crazyorchid commented
> Created a backend server from scratch and refactored the react code with components.

Please use the backend template we provided and edited and create a new branch and edit on it. Do not commit node_modules. Check out .gitignore on what you should not push to the remote.

2022-05-02 23:37 UTC, Crazyorchid commented on src/App.tsx
>    const API_URL = "http://localhost:5001/todos/";
RESTful please. 5001?

2022-05-03 00:52 UTC, NorrisWu0 commented on src/App.tsx
> +  // fetch all todos and set todos state
API functions can be decoupled into a separate file

2022-05-03 00:53 UTC, NorrisWu0 commented on src/App.tsx
>    const API_URL = "http://localhost:5001/todos/";
Try to think of the backend has multiple endpoints, don't just use one constant for each endpoint.

2022-05-03 01:11 UTC, NorrisWu0 commented on src/components/header/AppHeader.jsx
> +const AppHeader = () => {
Having this in its own component is pretty good, nice job.

2022-05-03 01:12 UTC, NorrisWu0 commented on src/components/section/AppSection.jsx
> +const AppSection = (props) => {
But why this is in its own component?

2022-05-03 01:15 UTC, NorrisWu0 commented on src/App.tsx
> +      <AppSection>
Okay, maybe explain how this component is structured?

2022-05-03 01:28 UTC, Crazyorchid commented on backend/server.js
> +        task: req.body.task,
Please add restrictions to request body

2022-05-03 01:30 UTC, Crazyorchid commented on backend/server.js
> +    todos[index].completed = true
This way only works for this temp frontend, what if you have a database or temp storage?

2022-05-03 01:30 UTC, Crazyorchid commented on backend/server.js
> +    todos.splice(index, 1)
Same here

2022-05-03 01:36 UTC, Crazyorchid requested changes
- Make sure you have proper routes and controllers if you want to setup your own server. 
- Please do not commit `node_modules`  (e.g. using `.gitignore`)
- Make sure you are using RESTful API formats with different endpoints
- Adding requirements to request bodies (Critical bugs on your frontend caused by this problem)

2022-05-03 01:46 UTC, NorrisWu0 commented on src/components/todo/Todo.jsx
> +const Todo = ({todos, completeTask, removeTask}) => {
This works, but if the component is nested deeper, you will need to pass the `completeTask` and `removeTask` multiple times. This is another good thing about decoupling the endpoint function, you can just import them when you need them.

2022-05-03 02:07 UTC, pycxu commented
@NorrisWu0 @Crazyorchid Thanks for the review! I will think about how to better structure/decouple the frontend. I am new to backend and the model/mutiendpoint concept; I will have a look at the backend repo and try to create a new branch.

2022-05-03 20:30 UTC, closed without merging